### ISSUE TITLE
Object is a reserved word as of PHP 7.2

### ISSUE THREAD

**Issue by scottrudy** [oat-sa/qti-sdk#119]
The Object QTI class located in src\qtism\data\content\xhtml\Object.php conflicts with a reserved word in PHP 7.2. The Content Marshaller class located in  src\qtism\data\storage\xml\marshalling\ContentMarshaller.php is at least one file that relies on this class. The naming of that class and use clause prevent the qti-sdk from functioning properly.

**Comment by bugalot** [comment]
Understood thank you very much for your report. I will proceed with a bugfix as soon as I can!

**Comment by scottrudy** [comment]
Thanks Jérôme. This looks like it would end up being a breaking change, but I appreciate you looking into it.

**Comment by bugalot** [comment]
Hello @scottrudy ! PHP 7.2 support is now available in version `10.0.0`. The `qtism\data\content\xhtml\Object` class has been changed into `qtism\data\content\xhtml\ObjectElement`.

All the best,
Jérôme
