### ISSUE TITLE
Support for v2p2p2.xsd

### ISSUE THREAD

**Issue by Blad3Danc3R** [oat-sa/qti-sdk#143]
Hello,

I would like to ask if there is any plan to start supporting the 
http://www.imsglobal.org/xsd/qti/qtiv2p2/imsqti_v2p2p2.xsd schema in the library.

Currently, when it tries to inferVersion it only supports 2.2.0 and 2.2.1 when we talk about QTI 2.2 overall.

Here is the code for reference
https://github.com/oat-sa/qti-sdk/blob/11.3.0/src/qtism/data/storage/xml/Utils.php#L91

**Comment by bugalot** [comment]
It's in the pipeline @Blad3Danc3R ! I'm just curious, what is your usage of QTI-SDK ? :slightly_smiling_face:

**Comment by julien-sebire** [comment]
Hi @Blad3Danc3R ,
I'm taking on this issue and will keep you informed.
Btw could you tell us more about your use case and maybe provide some 2.2.2 item sample(s) please?

**Comment by Blad3Danc3R** [comment]
I am sorry, I can't share my use cases, but I am thankful for your answers!

**Comment by julien-sebire** [comment]
Hi @Blad3Danc3R 
Release https://github.com/oat-sa/qti-sdk/releases/tag/12.1.0 adds the support for QTI 2.2.2 format.
No parsing has been changed though, only schema version. Feel free to open a new issue if you have any problem with some specific files.
