### ISSUE TITLE
getting the outcome value for each individual interaction

### ISSUE THREAD

**Issue by cheungkonghou** [oat-sa/qti-sdk#85]
Hi,

Is it possible to get the outcome value for each individual interaction, instead of getting a total sum of the SCORE, without splitting the outcome declaration into multiples?
The isCorrect() of ResponseVariable is not useful in this case since it compares the correct response only.
Thanks

**Comment by cheungkonghou** [comment]
Hi,

Another issue I encountered is it throws error when some specific xhtml elements exist in the QTI xml.
PHP Fatal error:  require_once(): Failed opening required '.../qtism/data/content/xhtml/Span.php'
PHP Fatal error:  require_once(): Failed opening required '.../qtism/data/content/xhtml/SpanElement.php'
PHP Fatal error:  require_once(): Failed opening required '.../qtism/data/content/xhtml/StrongElement.php'

I cannot find any SpanElement.php or StrongElement.php files in the source. Is there something wrong?

Thanks

**Comment by bugalot** [comment]
Hi @cheungkonghou !

Thanks for your interest in QTI-SDK! Let me ask you some more information about the two issues you reported.

> Another issue I encountered is it throws error when some specific xhtml elements exist in the QTI xml.
> PHP Fatal error: require_once(): Failed opening required '.../qtism/data/content/xhtml/Span.php'
> PHP Fatal error: require_once(): Failed opening required '.../qtism/data/content/xhtml/SpanElement.php'
> PHP Fatal error: require_once(): Failed opening required '.../qtism/data/content/xhtml/StrongElement.php'
> 
> I cannot find any SpanElement.php or StrongElement.php files in the source. Is there something wrong?

It's very difficult for me to help you without a QTI xml sample that produce such an error. I tried, but could not reproduce the issue. I'm very interested with this issue and really want to help. Could you please give me a QTI xml sample that throws the error so that I can have set a diagnostic?

> Is it possible to get the outcome value for each individual interaction, instead of getting a total sum of the SCORE, without splitting the outcome declaration into multiples?
> The isCorrect() of ResponseVariable is not useful in this case since it compares the correct response only.

I'm not sure I totally understood the problem you encounter. Could you please illustrate with an example? I will be happy to help!

All the best,
Jérôme

**Comment by cheungkonghou** [comment]
Hi @bugalot,

I produced the sample codes here:
[test.zip](https://github.com/oat-sa/qti-sdk/files/1006352/test.zip)
I run it on php5.6 without installing the lib with composer. (is it related?)

For the second issue, what I mean is there can be several responses in QTI (say, RESPONSE and RESPONSE_1). How can I get individual correctness for each response? Now the output score is something like 
print_r($itemSession['SCORE']); // gives 2
but I want something like
SCORE => array('RESPONSE' => 1, 'RESPONSE_1' => 1);

**Comment by tverhoof** [comment]
Hello @cheungkonghou! As we use the method class_exists to lookup classes as we load them, it's possible to have unexisting class names entering your autoload function.

By changing your autoload function like this, your code will work :

```php
if($paths1[0] == 'qtism'){
        $filepath = $libpath . $class_name . '.php';
        if (file_exists($filepath)) {
            require_once($filepath);
        }
    }
```
I hope this will solve your issue !

**Comment by cheungkonghou** [comment]
Hi @bugalot ,

The require error is fixed now. 
Just wanna know if we can get the outcome score result for each response rather than a total score, since it would be good for the user to know which response is correct and which is wrong.

Thanks
